name: Launch AWS WorkSpace

on:
  workflow_dispatch:
    inputs:
      workspace_username:
        description: "Directory username for the WorkSpace"
        required: true
      workspace_password:
        description: "Password to set for the user"
        required: true

jobs:
  start-workspace:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION || 'us-east-1' }}

      - name: Start WorkSpace
        id: workspace
        run: |
          set -e
          WS_ID="${{ secrets.AWS_WORKSPACE_ID }}"
          if [ -n "$WS_ID" ]; then
            if ! aws workspaces describe-workspaces --workspace-ids "$WS_ID" >/dev/null 2>&1; then
              WS_ID=""
            fi
          fi

          if [ -z "$WS_ID" ]; then
            WS_ID=$(aws workspaces create-workspaces \
              --workspaces DirectoryId=${{ secrets.AWS_DIRECTORY_ID }},UserName=${{ inputs.workspace_username }},BundleId=${{ secrets.AWS_BUNDLE_ID }},WorkspaceProperties={RunningMode=AUTO_STOP,RunningModeAutoStopTimeoutInMinutes=300} \
              --query 'PendingRequests[0].WorkspaceId' --output text)
          else
            aws workspaces modify-workspace-properties --workspace-id "$WS_ID" --workspace-properties RunningMode=AUTO_STOP,RunningModeAutoStopTimeoutInMinutes=300
          fi

          aws workspaces start-workspaces --start-workspace-requests WorkspaceId=$WS_ID
          echo "id=$WS_ID" >> "$GITHUB_OUTPUT"

      - name: Get directory info
        id: directory
        run: |
          DIR_ID=$(aws workspaces describe-workspaces --workspace-ids ${{ steps.workspace.outputs.id }} --query 'Workspaces[0].DirectoryId' --output text)
          REG_CODE=$(aws workspaces describe-workspace-directories --directory-ids "$DIR_ID" --query 'Directories[0].RegistrationCode' --output text)
          echo "dir=$DIR_ID" >> "$GITHUB_OUTPUT"
          echo "code=$REG_CODE" >> "$GITHUB_OUTPUT"

      - name: Set WorkSpace password
        run: |
          aws ds reset-user-password --directory-id ${{ steps.directory.outputs.dir }} --user-name "${{ inputs.workspace_username }}" --new-password "${{ inputs.workspace_password }}"

      - name: Connection instructions
        run: |
          echo "The WorkSpace is starting."
          echo "Once it is running you can connect using the AWS WorkSpaces client:"
          echo "https://clients.amazonworkspaces.com/"
          echo "Registration code: ${{ steps.directory.outputs.code }}"
          echo "Username: ${{ inputs.workspace_username }}"
          echo "Use the password you provided when launching the workflow."

