name: Launch AWS WorkSpace

on:
  workflow_dispatch:

jobs:
  start-workspace:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION || 'us-east-1' }}

      - name: Start WorkSpace
        run: |
          aws workspaces start-workspaces --start-workspace-requests WorkspaceId=${{ secrets.AWS_WORKSPACE_ID }}
          aws workspaces modify-workspace-properties --workspace-id ${{ secrets.AWS_WORKSPACE_ID }} --workspace-properties RunningMode=AUTO_STOP,RunningModeAutoStopTimeoutInMinutes=300

      - name: Get registration code
        id: regcode
        run: |
          DIR_ID=$(aws workspaces describe-workspaces --workspace-ids ${{ secrets.AWS_WORKSPACE_ID }} --query 'Workspaces[0].DirectoryId' --output text)
          REG_CODE=$(aws workspaces describe-workspace-directories --directory-ids "$DIR_ID" --query 'Directories[0].RegistrationCode' --output text)
          echo "code=$REG_CODE" >> "$GITHUB_OUTPUT"

      - name: Connection instructions
        run: |
          echo "The WorkSpace is starting."
          echo "Once it is running you can connect using the AWS WorkSpaces client:"
          echo "https://clients.amazonworkspaces.com/"
          echo "Registration code: ${{ steps.regcode.outputs.code }}"
          echo "Sign in with your WorkSpace username and password."

